[package]
name = "aetherflow"
version = "1.0.7"
description = "AetherFlow — High-Performance Windows Desktop Engine & Live Visuals Platform"
authors = ["AetherFlow"]
license = "MIT"
repository = "https://github.com/aetherflow/aetherflow"
edition = "2021"
default-run = "aetherflow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
tauri-plugin-notification = "2"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
# Shrink binary size
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Pipes",
    "Win32_System_JobObjects",
    "Win32_UI_Shell"
] }
